### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by lr8616** [CurtisColwell/StrainViz#42]
Hi! 

 During running the StrainViz.bash, I met the following error  and had no idea how to solve it. Could you kindly help me? Thanks! Before meeting this error, the Gaussian jobs have been done.

Traceback (most recent call last):
  File "scripts/StrainViz.py", line 15, in <module>
    bond, angle, dihedral = map_forces("input/" + geometry_filename, file)
  File "/home/gauss/computation/LR/StrainViz-1.1/scripts/bond_scripts.py", line 35, in map_forces
    bond_forces_vmd, bond_min, bond_max = vmd_norm(mapped_bond_forces)
  File "/home/gauss/computation/LR/StrainViz-1.1/scripts/bond_scripts.py", line 159, in vmd_norm
    minimum = copy.deepcopy(min(norm_values))
ValueError: min() arg is an empty sequence

**Comment by lr8616** [comment]
I have solved this problem. Thank you!

**Comment by CurtisColwell** [comment]
Hi, sorry for the late reply. This is an operational problem that I've run into before. It has been a while... 

The normalized values are not being generated I think it is from a problem with the values derived from the starting fragments and the resulting relaxed state.

Can you share your inputs? Either here or through my former email: ccolwell@uoregon.edu

**Comment by CurtisColwell** [comment]
Awesome! Thanks for the feedback.
