### ISSUE TITLE
Problem in reproducing the results. 

### ISSUE THREAD

**Issue by Flumar89** [CurtisColwell/StrainViz#44]
Hi:
I tried to reproduce the figure 5 (7cpp) of your paper and it turns out that when I use your fragments (from the SI of the paper) I have the same results in total strain etc etc. However, when I do the fragmentation in Avogadro, I have different values (difference ca 3kcal/mol). As atoms are not numbered, how can I know that I did the correct fragmentation?
All the best
Thanks

**Comment by CurtisColwell** [comment]
Hello! 3 kcal/mol difference is very close. You are probably doing everything correctly, but are using different rotamers. I would check the dihedral angle between phenylenes for the one you did yourself.
